package com.breynisson.rubiks;

import static com.breynisson.rubiks.Side.*;

enum Position {
    FRONT_TOP_LEFT(FRONT),
    FRONT_TOP_MIDDLE(FRONT),
    FRONT_TOP_RIGHT(FRONT),
    FRONT_MIDDLE_LEFT(FRONT),
    FRONT_MIDDLE_MIDDLE(FRONT),
    FRONT_MIDDLE_RIGHT(FRONT),
    FRONT_BOTTOM_LEFT(FRONT),
    FRONT_BOTTOM_MIDDLE(FRONT),
    FRONT_BOTTOM_RIGHT(FRONT),

    TOP_FRONT_LEFT(TOP),
    TOP_FRONT_MIDDLE(TOP),
    TOP_FRONT_RIGHT(TOP),
    TOP_MIDDLE_LEFT(TOP),
    TOP_MIDDLE_MIDDLE(TOP),
    TOP_MIDDLE_RIGHT(TOP),
    TOP_BACK_LEFT(TOP),
    TOP_BACK_MIDDLE(TOP),
    TOP_BACK_RIGHT(TOP),

    LEFT_FRONT_TOP(LEFT),
    LEFT_FRONT_MIDDLE(LEFT),
    LEFT_FRONT_BOTTOM(LEFT),
    LEFT_MIDDLE_TOP(LEFT),
    LEFT_MIDDLE_MIDDLE(LEFT),
    LEFT_MIDDLE_BOTTOM(LEFT),
    LEFT_BACK_TOP(LEFT),
    LEFT_BACK_MIDDLE(LEFT),
    LEFT_BACK_BOTTOM(LEFT),

    RIGHT_FRONT_TOP(RIGHT),
    RIGHT_FRONT_MIDDLE(RIGHT),
    RIGHT_FRONT_BOTTOM(RIGHT),
    RIGHT_MIDDLE_TOP(RIGHT),
    RIGHT_MIDDLE_MIDDLE(RIGHT),
    RIGHT_MIDDLE_BOTTOM(RIGHT),
    RIGHT_BACK_TOP(RIGHT),
    RIGHT_BACK_MIDDLE(RIGHT),
    RIGHT_BACK_BOTTOM(RIGHT),

    BOTTOM_FRONT_LEFT(BOTTOM),
    BOTTOM_FRONT_MIDDLE(BOTTOM),
    BOTTOM_FRONT_RIGHT(BOTTOM),
    BOTTOM_MIDDLE_LEFT(BOTTOM),
    BOTTOM_MIDDLE_MIDDLE(BOTTOM),
    BOTTOM_MIDDLE_RIGHT(BOTTOM),
    BOTTOM_BACK_LEFT(BOTTOM),
    BOTTOM_BACK_MIDDLE(BOTTOM),
    BOTTOM_BACK_RIGHT(BOTTOM),

    BACK_TOP_LEFT(BACK),
    BACK_TOP_MIDDLE(BACK),
    BACK_TOP_RIGHT(BACK),
    BACK_MIDDLE_LEFT(BACK),
    BACK_MIDDLE_MIDDLE(BACK),
    BACK_MIDDLE_RIGHT(BACK),
    BACK_BOTTOM_LEFT(BACK),
    BACK_BOTTOM_MIDDLE(BACK),
    BACK_BOTTOM_RIGHT(BACK)
    ;
    public final Side side;
    Position(Side side) {
        this.side = side;
    }
}
